import type {
  ComponentConfirmMockCase,
  ComponentFormOption,
  ComponentListPreviewItem,
  ComponentModalPreviewField,
  ComponentToastPreviewItem,
} from '@/features/component-library/useComponentLibraryDomain'

export const componentListMockItems: ComponentListPreviewItem[] = [
  {
    id: 'list-analytics',
    title: '用户增长分析看板（含跨端数据回流）',
    subtitle: '增长运营 · P0',
    description: '展示完整信息：头像、标签、状态、描述、进度、操作区；用于验证高密度信息行。',
    tags: ['数据看板', '长标题', 'P0'],
    owner: '王敏',
    updatedAt: '2026-03-31 22:18',
    progress: 82,
    avatarText: '增',
    tone: 'success',
    pinned: true,
    soonDue: true,
  },
  {
    id: 'list-auth',
    title: '认证中心改版',
    subtitle: '架构升级 · P1',
    description: '中等文本长度，验证列表标准行高和 hover/active 反馈。',
    tags: ['重构', '安全'],
    owner: '李哲',
    updatedAt: '2026-03-31 16:40',
    progress: 56,
    avatarText: '鉴',
    tone: 'default',
  },
  {
    id: 'list-ai',
    title: 'AI 助手提示词实验',
    subtitle: '模型能力 · Lab',
    description: '用于验证 warning 态、标签较多时的换行与截断策略。',
    tags: ['试验', 'A/B', '标签较多', '提示词', '可回滚'],
    owner: '赵悦',
    updatedAt: '2026-03-30 19:05',
    progress: 34,
    avatarText: '试',
    tone: 'warning',
  },
  {
    id: 'list-risk',
    title: '支付链路异常监控',
    subtitle: '风控专项 · S1',
    description: '危险态样式校验：边框、状态色、强调文本。',
    tags: ['告警', '稳定性'],
    owner: '陈卓',
    updatedAt: '2026-03-30 09:12',
    progress: 20,
    avatarText: '警',
    tone: 'danger',
    soonDue: true,
  },
  {
    id: 'list-legacy',
    title: '历史组件迁移',
    subtitle: '遗留治理 · Backlog',
    description: '禁用态样式：降低对比度、禁用按钮、不可选中。',
    tags: ['迁移'],
    owner: '周航',
    updatedAt: '2026-03-28 14:21',
    progress: 8,
    avatarText: '迁',
    tone: 'muted',
    disabled: true,
  },
  {
    id: 'list-empty-desc',
    title: '只展示标题与元信息',
    subtitle: '简版样式 · P3',
    description: '',
    tags: [],
    owner: '韩雪',
    updatedAt: '2026-03-27 10:05',
    progress: 0,
    avatarText: '简',
    tone: 'default',
  },
  {
    id: 'list-long-desc',
    title: '超长描述内容示例',
    subtitle: '内容可读性验证',
    description:
      '这是一条用于验证描述折行、最大宽度和可读性的 mock 数据。它会覆盖多行文本、长句、以及中英文混排场景，确保列表在复杂真实数据下也保持稳定布局。',
    tags: ['长描述', '排版'],
    owner: '孙宁',
    updatedAt: '2026-03-26 20:49',
    progress: 63,
    avatarText: '排',
    tone: 'success',
  },
  {
    id: 'list-release',
    title: '版本发布前检查',
    subtitle: 'Release · Checklist',
    description: '进度 100% 与 pinned 样式校验。',
    tags: ['上线', 'Checklist'],
    owner: '何嘉',
    updatedAt: '2026-03-25 12:03',
    progress: 100,
    avatarText: '发',
    tone: 'success',
    pinned: true,
  },
]

export const componentModalMockFields: ComponentModalPreviewField[] = [
  { id: 'modal-field-bug', label: '缺陷标题', kind: 'text', value: '点击「确认发布」后白屏，需二次刷新恢复' },
  { id: 'modal-field-stage', label: '发现环节', kind: 'tags', tags: ['回归测试', 'Android', '灰度环境'] },
  { id: 'modal-field-category', label: '缺陷分类', kind: 'tags', tags: ['交互异常', '状态同步'] },
  { id: 'modal-field-created', label: '创建时间', kind: 'datetime', value: '2026-04-01 10:42:19' },
  { id: 'modal-field-requirement', label: '关联需求', kind: 'link', value: 'REQ-4019 订单详情改版', href: 'https://project.feishu.cn' },
  { id: 'modal-field-blocking', label: '是否阻塞发布', kind: 'boolean', boolValue: true },
  {
    id: 'modal-field-desc',
    label: '复现步骤',
    kind: 'multiline',
    value:
      '1. 登录测试账号并进入订单页\\n2. 快速切换筛选条件后点击确认发布\\n3. 页面闪烁后出现白屏，控制台提示 undefined state',
  },
  { id: 'modal-field-path', label: '影响路径', kind: 'path', value: '/src/modules/order/detail/confirm-flow.ts' },
  {
    id: 'modal-field-code',
    label: '修复片段',
    kind: 'code',
    value: "if (!snapshot?.ready) return { ok: false, reason: 'snapshot-not-ready' }\\nawait nextTick()\\nreturn applyPublish(payload)",
  },
  {
    id: 'modal-field-json',
    label: '扩展信息',
    kind: 'json',
    value: '{\\n  "traceId": "bf2a3a2f-8f9a-4c57-9c7f-1a0ef2c35ed9",\\n  "build": "v2.18.0-rc.3",\\n  "owner": "订单前端组"\\n}',
  },
]

export const componentConfirmMockCases: ComponentConfirmMockCase[] = [
  {
    id: 'confirm-default',
    tone: 'default',
    title: '确认批量推进排期',
    description: '将 6 条待办推进到下一节点，系统会自动记录执行人和时间。',
    confirmLabel: '确认推进',
    cancelLabel: '取消',
  },
  {
    id: 'confirm-warning',
    tone: 'warning',
    title: '确认回滚当前版本',
    description: '回滚后会触发灰度撤回，并通知相关负责人。',
    confirmLabel: '继续回滚',
    cancelLabel: '再想想',
  },
  {
    id: 'confirm-danger',
    tone: 'danger',
    title: '永久删除缺陷记录',
    description: '该操作不可恢复。请确认你已经完成归档。',
    confirmLabel: '永久删除',
    cancelLabel: '取消',
    requiresInput: true,
    inputHint: '请输入 DELETE 以确认操作',
  },
  {
    id: 'confirm-loading',
    tone: 'success',
    title: '发布确认',
    description: '系统正在校验发布单和风控规则。',
    confirmLabel: '提交发布',
    cancelLabel: '取消',
    loading: true,
  },
]

export const componentToastMockItems: ComponentToastPreviewItem[] = [
  { id: 'toast-info', tone: 'info', title: '信息提示', message: '已同步最新配置。' },
  { id: 'toast-success', tone: 'success', title: '提交成功', message: '缺陷已绑定到飞书。', actionLabel: '查看详情' },
  { id: 'toast-warning', tone: 'warning', title: '风险提醒', message: '当前变更未通过全部检查。' },
  { id: 'toast-danger', tone: 'danger', title: '操作失败', message: '网络异常，请稍后重试。', actionLabel: '重试' },
  { id: 'toast-loading', tone: 'loading', title: '处理中', message: '正在批量推进排期，请稍候。', sticky: true },
  { id: 'toast-default', tone: 'default', title: '普通通知', message: '你有一条新的待办。' },
]

export const componentFormSelectOptions: ComponentFormOption[] = [
  { label: 'Bug 修复', value: 'bugfix' },
  { label: '体验优化', value: 'ux' },
  { label: '技术重构', value: 'refactor' },
  { label: '实验功能', value: 'experiment' },
]

export const componentFormRadioOptions: ComponentFormOption[] = [
  { label: 'P0（阻塞）', value: 'p0' },
  { label: 'P1（高）', value: 'p1' },
  { label: 'P2（中）', value: 'p2' },
  { label: 'P3（低）', value: 'p3' },
]
