import type { ComputedRef, Ref } from 'vue'

type ComponentSettingsSubMenu = 'list' | 'modal' | 'confirm' | 'toast' | 'form' | 'icon'
type ModelSettingsSubMenu = 'management'
type BugTraceSubMenu = 'trace' | 'inbox'
type MaybeRef<T> = Ref<T> | ComputedRef<T>

interface UseAppPanelContextsUiState {
  sessionListCollapsed: unknown
  keyword: unknown
  useVectorSearch: unknown
  advancedFiltersOpen: unknown
  activeProvider: MaybeRef<string>
  componentSettingsSubMenu: MaybeRef<ComponentSettingsSubMenu>
  modelSettingsSubMenu: MaybeRef<ModelSettingsSubMenu>
  cursorConversationIdFilter: unknown
  providerFilter: unknown
  timeRangePreset: unknown
  tagFilter: unknown
  selectedSessionId: unknown
  flowRef: unknown
  anchoredNodeId: unknown
  presetTags: readonly string[]
  bugTraceSubMenu: MaybeRef<BugTraceSubMenu>
}

interface UseAppPanelContextsViewModes {
  isComponentLibraryMode: MaybeRef<boolean>
  isComponentLibraryListMode: MaybeRef<boolean>
  isComponentLibraryModalMode: MaybeRef<boolean>
  isComponentLibraryConfirmMode: MaybeRef<boolean>
  isComponentLibraryToastMode: MaybeRef<boolean>
  isComponentLibraryFormMode: MaybeRef<boolean>
  isComponentLibraryIconMode: MaybeRef<boolean>
  isModelSettingsMode: MaybeRef<boolean>
  isKnowledgeSourcesMode: MaybeRef<boolean>
}

interface UseAppPanelContextsOptions {
  uiState: UseAppPanelContextsUiState
  flags: {
    isBugLocatorMode: MaybeRef<boolean>
    isFeishuScheduleMode: MaybeRef<boolean>
  }
  viewModes: UseAppPanelContextsViewModes
  uiToastDomain: Record<string, unknown>
  bugTraceDomain: Record<string, unknown>
  componentLibraryDomain: Record<string, unknown>
  knowledgeSourcesDomain: Record<string, unknown>
  bugInboxFeishuDomain: Record<string, unknown>
  wikiVaultSyncDomain: Record<string, unknown>
  sessionFilterDomain: Record<string, unknown>
  sessionFlowDomain: Record<string, unknown>
  sessionPresentationDomain: Record<string, unknown>
  sessionDataDomain: Record<string, unknown>
  messageTagDomain: Record<string, unknown>
  promptScoreDomain: Record<string, unknown>
  modelSettingsDomain: Record<string, unknown>
  feishuProjectSettingsDomain: Record<string, unknown>
  patchDirSettingsDomain: Record<string, unknown>
  importDomain: Record<string, unknown>
  displayFormatDomain: Record<string, unknown>
}

export function useAppPanelContexts(options: UseAppPanelContextsOptions) {
  const {
    uiState,
    flags,
    viewModes,
    uiToastDomain,
    bugTraceDomain,
    componentLibraryDomain,
    knowledgeSourcesDomain,
    bugInboxFeishuDomain,
    wikiVaultSyncDomain,
    sessionFilterDomain,
    sessionFlowDomain,
    sessionPresentationDomain,
    sessionDataDomain,
    messageTagDomain,
    promptScoreDomain,
    modelSettingsDomain,
    feishuProjectSettingsDomain,
    patchDirSettingsDomain,
    importDomain,
    displayFormatDomain,
  } = options

  const bugLocatorPanelCtx = {
    isBugLocatorMode: flags.isBugLocatorMode,
    bugTraceSubMenu: uiState.bugTraceSubMenu,
    bugTraceCode: bugTraceDomain.bugTraceCode,
    selectedPatchDirPresetId: patchDirSettingsDomain.selectedPatchDirPresetId,
    patchDirPresets: patchDirSettingsDomain.patchDirPresets,
    bugTraceCursorRoot: bugTraceDomain.bugTraceCursorRoot,
    bugTraceTopK: bugTraceDomain.bugTraceTopK,
    selectedPatchDirPreset: patchDirSettingsDomain.selectedPatchDirPreset,
    bugTracePatchTotal: bugTraceDomain.bugTracePatchTotal,
    runBugTrace: bugTraceDomain.runBugTrace,
    bugTraceLoading: bugTraceDomain.bugTraceLoading,
    resetBugTrace: bugTraceDomain.resetBugTrace,
    bugTraceError: bugTraceDomain.bugTraceError,
    bugTraceResult: bugTraceDomain.bugTraceResult,
    copyBugTraceConversationId: bugTraceDomain.copyBugTraceConversationId,
    bugTraceCopiedConversationId: bugTraceDomain.bugTraceCopiedConversationId,
    getBugTraceSnippetList: bugTraceDomain.getBugTraceSnippetList,
    renderBugTraceSnippetHtml: bugTraceDomain.renderBugTraceSnippetHtml,
    formatBugTraceSnippetSource: bugTraceDomain.formatBugTraceSnippetSource,
    getBugTraceMatchedLocationText: bugTraceDomain.getBugTraceMatchedLocationText,
    bugInboxDraftByPatchKey: bugInboxFeishuDomain.bugInboxDraftByPatchKey,
    getBugTraceCacheKey: bugTraceDomain.getBugTraceCacheKey,
    saveBugToInbox: bugInboxFeishuDomain.saveBugToInbox,
    bugInboxSavingKey: bugInboxFeishuDomain.bugInboxSavingKey,
    ensureConversationDetail: bugTraceDomain.ensureConversationDetail,
    toggleConversationDetail: bugTraceDomain.toggleConversationDetail,
    bugTraceConversationExpandedKey: bugTraceDomain.bugTraceConversationExpandedKey,
    getConversationCardKey: bugTraceDomain.getConversationCardKey,
    bugTraceConversationDetailLoadingKey: bugTraceDomain.bugTraceConversationDetailLoadingKey,
    getConversationDetail: bugTraceDomain.getConversationDetail,
    getVisibleConversationTurns: bugTraceDomain.getVisibleConversationTurns,
    renderMarkdown: displayFormatDomain.renderMarkdown,
    prepareBugTracePatch: bugTraceDomain.prepareBugTracePatch,
    toggleBugTracePatch: bugTraceDomain.toggleBugTracePatch,
    bugTraceExpandedPatch: bugTraceDomain.bugTraceExpandedPatch,
    bugTraceViewMode: bugTraceDomain.bugTraceViewMode,
    bugTraceFullViewMode: bugTraceDomain.bugTraceFullViewMode,
    bugTraceContextLines: bugTraceDomain.bugTraceContextLines,
    getBugTraceParsedFiles: bugTraceDomain.getBugTraceParsedFiles,
    toggleBugTraceFileTree: bugTraceDomain.toggleBugTraceFileTree,
    isBugTraceFileTreeCollapsed: bugTraceDomain.isBugTraceFileTreeCollapsed,
    getSelectedBugTraceFile: bugTraceDomain.getSelectedBugTraceFile,
    getBugTraceCodeMirrorModel: bugTraceDomain.getBugTraceCodeMirrorModel,
    selectBugTraceFile: bugTraceDomain.selectBugTraceFile,
    hasBugTraceFilePreview: bugTraceDomain.hasBugTraceFilePreview,
    getBugTraceFilePreview: bugTraceDomain.getBugTraceFilePreview,
    setBugTraceFullPreviewRef: bugTraceDomain.setBugTraceFullPreviewRef,
    onBugTraceFullPreviewScroll: bugTraceDomain.onBugTraceFullPreviewScroll,
    getBugTraceFullHighlightHtml: bugTraceDomain.getBugTraceFullHighlightHtml,
    bugTracePreviewLoadingKey: bugTraceDomain.bugTracePreviewLoadingKey,
    getBugTraceSelectedFileDiffHtml: bugTraceDomain.getBugTraceSelectedFileDiffHtml,
    getBugTraceDiffHtml: bugTraceDomain.getBugTraceDiffHtml,
    bugInboxError: bugInboxFeishuDomain.bugInboxError,
    bugInboxColumns: bugInboxFeishuDomain.bugInboxColumns,
    bugInboxItems: bugInboxFeishuDomain.bugInboxItems,
    bugInboxLoading: bugInboxFeishuDomain.bugInboxLoading,
    bugInboxUpdatingId: bugInboxFeishuDomain.bugInboxUpdatingId,
    BUG_INBOX_COLUMN_WIDTHS_STORAGE_KEY: bugInboxFeishuDomain.BUG_INBOX_COLUMN_WIDTHS_STORAGE_KEY,
    asBugInboxRow: bugInboxFeishuDomain.asBugInboxRow,
    copyBugInboxId: bugInboxFeishuDomain.copyBugInboxId,
    bugInboxCopiedId: bugInboxFeishuDomain.bugInboxCopiedId,
    getBugInboxFeishuLink: bugInboxFeishuDomain.getBugInboxFeishuLink,
    getBugBindStatus: bugInboxFeishuDomain.getBugBindStatus,
    getBugBindTime: bugInboxFeishuDomain.getBugBindTime,
    getBugBoundTitle: bugInboxFeishuDomain.getBugBoundTitle,
    getBugBoundOwner: bugInboxFeishuDomain.getBugBoundOwner,
    openBugInboxDetail: bugInboxFeishuDomain.openBugInboxDetail,
    openFeishuBindModal: bugInboxFeishuDomain.openFeishuBindModal,
    openBugInboxDeleteConfirm: bugInboxFeishuDomain.openBugInboxDeleteConfirm,
    updateBugInboxDescription: bugInboxFeishuDomain.updateBugInboxDescription,
    formatTime: displayFormatDomain.formatTime,
  }

  const componentLibraryPanelCtx = {
    activeProvider: uiState.activeProvider,
    componentSettingsSubMenu: uiState.componentSettingsSubMenu,
    isComponentLibraryMode: viewModes.isComponentLibraryMode,
    isComponentLibraryListMode: viewModes.isComponentLibraryListMode,
    componentListMockItems: componentLibraryDomain.componentListMockItems,
    componentListDensity: componentLibraryDomain.componentListDensity,
    componentListTone: componentLibraryDomain.componentListTone,
    componentListPreviewCount: componentLibraryDomain.componentListPreviewCount,
    componentListAsCards: componentLibraryDomain.componentListAsCards,
    componentListStriped: componentLibraryDomain.componentListStriped,
    componentListBordered: componentLibraryDomain.componentListBordered,
    componentListRounded: componentLibraryDomain.componentListRounded,
    componentListHoverable: componentLibraryDomain.componentListHoverable,
    componentListShowDividers: componentLibraryDomain.componentListShowDividers,
    componentListShowAvatar: componentLibraryDomain.componentListShowAvatar,
    componentListShowDescription: componentLibraryDomain.componentListShowDescription,
    componentListShowMeta: componentLibraryDomain.componentListShowMeta,
    componentListShowTags: componentLibraryDomain.componentListShowTags,
    componentListShowProgress: componentLibraryDomain.componentListShowProgress,
    componentListShowActions: componentLibraryDomain.componentListShowActions,
    componentListPreviewClass: componentLibraryDomain.componentListPreviewClass,
    componentListPreviewItems: componentLibraryDomain.componentListPreviewItems,
    componentListActiveId: componentLibraryDomain.componentListActiveId,
    getComponentListStatusLabel: componentLibraryDomain.getComponentListStatusLabel,
    isComponentLibraryModalMode: viewModes.isComponentLibraryModalMode,
    componentModalMockFields: componentLibraryDomain.componentModalMockFields,
    componentModalSize: componentLibraryDomain.componentModalSize,
    componentModalTone: componentLibraryDomain.componentModalTone,
    componentModalCompact: componentLibraryDomain.componentModalCompact,
    componentModalShowDivider: componentLibraryDomain.componentModalShowDivider,
    componentModalShowFooter: componentLibraryDomain.componentModalShowFooter,
    componentModalPreviewOpen: componentLibraryDomain.componentModalPreviewOpen,
    componentModalSurfaceClass: componentLibraryDomain.componentModalSurfaceClass,
    isComponentModalFieldCopyable: componentLibraryDomain.isComponentModalFieldCopyable,
    copyComponentModalFieldValue: componentLibraryDomain.copyComponentModalFieldValue,
    componentModalCopiedFieldId: componentLibraryDomain.componentModalCopiedFieldId,
    componentModalDialogClass: componentLibraryDomain.componentModalDialogClass,
    isComponentLibraryConfirmMode: viewModes.isComponentLibraryConfirmMode,
    componentConfirmMockCases: componentLibraryDomain.componentConfirmMockCases,
    componentConfirmTone: componentLibraryDomain.componentConfirmTone,
    componentConfirmShowDescription: componentLibraryDomain.componentConfirmShowDescription,
    componentConfirmRequireInput: componentLibraryDomain.componentConfirmRequireInput,
    componentConfirmKeyword: componentLibraryDomain.componentConfirmKeyword,
    componentConfirmInput: componentLibraryDomain.componentConfirmInput,
    isComponentConfirmSubmitDisabled: componentLibraryDomain.isComponentConfirmSubmitDisabled,
    componentConfirmLoading: componentLibraryDomain.componentConfirmLoading,
    componentConfirmPreviewOpen: componentLibraryDomain.componentConfirmPreviewOpen,
    componentConfirmSurfaceClass: componentLibraryDomain.componentConfirmSurfaceClass,
    runComponentConfirmSubmit: componentLibraryDomain.runComponentConfirmSubmit,
    isComponentLibraryFormMode: viewModes.isComponentLibraryFormMode,
    componentFormLayout: componentLibraryDomain.componentFormLayout,
    componentFormRadioDirection: componentLibraryDomain.componentFormRadioDirection,
    componentFormDisabled: componentLibraryDomain.componentFormDisabled,
    componentFormReadonly: componentLibraryDomain.componentFormReadonly,
    componentFormShowHint: componentLibraryDomain.componentFormShowHint,
    componentFormSimulateError: componentLibraryDomain.componentFormSimulateError,
    componentFormInputValue: componentLibraryDomain.componentFormInputValue,
    componentFormSelectValue: componentLibraryDomain.componentFormSelectValue,
    componentFormRadioValue: componentLibraryDomain.componentFormRadioValue,
    componentFormSelectOptions: componentLibraryDomain.componentFormSelectOptions,
    componentFormRadioOptions: componentLibraryDomain.componentFormRadioOptions,
    componentFormSurfaceClass: componentLibraryDomain.componentFormSurfaceClass,
    componentFormInputHint: componentLibraryDomain.componentFormInputHint,
    componentFormSelectHint: componentLibraryDomain.componentFormSelectHint,
    componentFormRadioHint: componentLibraryDomain.componentFormRadioHint,
    resetComponentFormPreview: componentLibraryDomain.resetComponentFormPreview,
    isComponentLibraryIconMode: viewModes.isComponentLibraryIconMode,
    componentIconKeyword: componentLibraryDomain.componentIconKeyword,
    componentIconItems: componentLibraryDomain.componentIconItems,
    componentIconFilteredItems: componentLibraryDomain.componentIconFilteredItems,
    componentIconUsedItems: componentLibraryDomain.componentIconUsedItems,
    componentIconUnusedItems: componentLibraryDomain.componentIconUnusedItems,
    isComponentLibraryToastMode: viewModes.isComponentLibraryToastMode,
    componentToastMockItems: componentLibraryDomain.componentToastMockItems,
    componentToastPosition: componentLibraryDomain.componentToastPosition,
    componentToastDurationMs: componentLibraryDomain.componentToastDurationMs,
    componentToastShowIcon: componentLibraryDomain.componentToastShowIcon,
    componentToastDense: componentLibraryDomain.componentToastDense,
    componentToastSticky: componentLibraryDomain.componentToastSticky,
    clearComponentToastQueue: componentLibraryDomain.clearComponentToastQueue,
    triggerComponentToast: componentLibraryDomain.triggerComponentToast,
    componentToastStackClass: componentLibraryDomain.componentToastStackClass,
    componentToastPreviewRuntimeItems: componentLibraryDomain.componentToastPreviewRuntimeItems,
    isRuntimeComponentToast: componentLibraryDomain.isRuntimeComponentToast,
    removeComponentToast: componentLibraryDomain.removeComponentToast,
  }

  const modelManagementPanelCtx = {
    activeProvider: uiState.activeProvider,
    modelSettingsSubMenu: uiState.modelSettingsSubMenu,
    isModelSettingsMode: viewModes.isModelSettingsMode,
    modelSettingsLoading: modelSettingsDomain.modelSettingsLoading,
    modelSettingsSaving: modelSettingsDomain.modelSettingsSaving,
    modelManagementItems: modelSettingsDomain.modelManagementItems,
    selectedModelSettingsItem: modelSettingsDomain.selectedModelSettingsItem,
    loadModelSettings: modelSettingsDomain.loadModelSettings,
    openModelSettings: modelSettingsDomain.openModelSettings,
  }

  const knowledgeSourcesPanelCtx = {
    isKnowledgeSourcesMode: viewModes.isKnowledgeSourcesMode,
    workbenchTab: knowledgeSourcesDomain.workbenchTab,
    workbenchTabs: knowledgeSourcesDomain.workbenchTabs,
    workbenchHero: knowledgeSourcesDomain.workbenchHero,
    knowledgeItems: knowledgeSourcesDomain.knowledgeItems,
    knowledgeStats: knowledgeSourcesDomain.knowledgeStats,
    knowledgeLoading: knowledgeSourcesDomain.knowledgeLoading,
    knowledgeSaving: knowledgeSourcesDomain.knowledgeSaving,
    selectedKnowledgeItemId: knowledgeSourcesDomain.selectedKnowledgeItemId,
    selectedKnowledgeItem: knowledgeSourcesDomain.selectedKnowledgeItem,
    filteredKnowledgeItems: knowledgeSourcesDomain.filteredKnowledgeItems,
    knowledgeSourceTypeFilter: knowledgeSourcesDomain.knowledgeSourceTypeFilter,
    knowledgeStatusFilter: knowledgeSourcesDomain.knowledgeStatusFilter,
    knowledgeIntakeStageFilter: knowledgeSourcesDomain.knowledgeIntakeStageFilter,
    knowledgeConfidenceFilter: knowledgeSourcesDomain.knowledgeConfidenceFilter,
    knowledgeKeyword: knowledgeSourcesDomain.knowledgeKeyword,
    summaryCards: knowledgeSourcesDomain.summaryCards,
    sourceTypeOptions: knowledgeSourcesDomain.sourceTypeOptions,
    statusOptions: knowledgeSourcesDomain.statusOptions,
    intakeStageOptions: knowledgeSourcesDomain.intakeStageOptions,
    confidenceOptions: knowledgeSourcesDomain.confidenceOptions,
    subtypeSuggestions: knowledgeSourcesDomain.subtypeSuggestions,
    editorIntakeStageOption: knowledgeSourcesDomain.editorIntakeStageOption,
    editorConfidenceOption: knowledgeSourcesDomain.editorConfidenceOption,
    editorIntakeSummary: knowledgeSourcesDomain.editorIntakeSummary,
    editorId: knowledgeSourcesDomain.editorId,
    editorSourceType: knowledgeSourcesDomain.editorSourceType,
    editorSourceSubtype: knowledgeSourcesDomain.editorSourceSubtype,
    editorStatus: knowledgeSourcesDomain.editorStatus,
    editorTitle: knowledgeSourcesDomain.editorTitle,
    editorContent: knowledgeSourcesDomain.editorContent,
    editorSourceUrl: knowledgeSourcesDomain.editorSourceUrl,
    editorSourceFile: knowledgeSourcesDomain.editorSourceFile,
    editorTagsInput: knowledgeSourcesDomain.editorTagsInput,
    editorProject: knowledgeSourcesDomain.editorProject,
    editorTopic: knowledgeSourcesDomain.editorTopic,
    editorIntakeStage: knowledgeSourcesDomain.editorIntakeStage,
    editorConfidence: knowledgeSourcesDomain.editorConfidence,
    editorKeyQuestion: knowledgeSourcesDomain.editorKeyQuestion,
    editorDecisionNote: knowledgeSourcesDomain.editorDecisionNote,
    editorPreview: knowledgeSourcesDomain.editorPreview,
    editorDuplicateCandidates: knowledgeSourcesDomain.editorDuplicateCandidates,
    quickCaptureOpen: knowledgeSourcesDomain.quickCaptureOpen,
    quickCaptureSaving: knowledgeSourcesDomain.quickCaptureSaving,
    quickCaptureMode: knowledgeSourcesDomain.quickCaptureMode,
    quickCaptureSourceType: knowledgeSourcesDomain.quickCaptureSourceType,
    quickCaptureTitle: knowledgeSourcesDomain.quickCaptureTitle,
    quickCaptureContent: knowledgeSourcesDomain.quickCaptureContent,
    quickCaptureSourceUrl: knowledgeSourcesDomain.quickCaptureSourceUrl,
    quickCaptureTagsInput: knowledgeSourcesDomain.quickCaptureTagsInput,
    quickCaptureMarkActive: knowledgeSourcesDomain.quickCaptureMarkActive,
    quickCaptureProject: knowledgeSourcesDomain.quickCaptureProject,
    quickCaptureTopic: knowledgeSourcesDomain.quickCaptureTopic,
    quickCaptureIntakeStage: knowledgeSourcesDomain.quickCaptureIntakeStage,
    quickCaptureConfidence: knowledgeSourcesDomain.quickCaptureConfidence,
    quickCaptureDecisionNote: knowledgeSourcesDomain.quickCaptureDecisionNote,
    quickCapturePreview: knowledgeSourcesDomain.quickCapturePreview,
    quickCaptureBatchEntries: knowledgeSourcesDomain.quickCaptureBatchEntries,
    quickCaptureCanSave: knowledgeSourcesDomain.quickCaptureCanSave,
    quickCaptureSummary: knowledgeSourcesDomain.quickCaptureSummary,
    batchImportOpen: knowledgeSourcesDomain.batchImportOpen,
    batchImportText: knowledgeSourcesDomain.batchImportText,
    batchImportDuplicateMode: knowledgeSourcesDomain.batchImportDuplicateMode,
    batchImportSaving: knowledgeSourcesDomain.batchImportSaving,
    batchImportRows: knowledgeSourcesDomain.batchImportRows,
    batchImportReadyCount: knowledgeSourcesDomain.batchImportReadyCount,
    batchImportDuplicateCount: knowledgeSourcesDomain.batchImportDuplicateCount,
    batchImportMergeCount: knowledgeSourcesDomain.batchImportMergeCount,
    batchImportError: knowledgeSourcesDomain.batchImportError,
    openClawSyncOpen: knowledgeSourcesDomain.openClawSyncOpen,
    openClawSyncLoading: knowledgeSourcesDomain.openClawSyncLoading,
    openClawSyncImporting: knowledgeSourcesDomain.openClawSyncImporting,
    openClawSyncPreview: knowledgeSourcesDomain.openClawSyncPreview,
    openClawSyncRows: knowledgeSourcesDomain.openClawSyncRows,
    openClawSyncSummary: knowledgeSourcesDomain.openClawSyncSummary,
    openClawSyncError: knowledgeSourcesDomain.openClawSyncError,
    openClawSyncCanImport: knowledgeSourcesDomain.openClawSyncCanImport,
    taskReviewLoading: knowledgeSourcesDomain.taskReviewLoading,
    taskReviewUpdatingId: knowledgeSourcesDomain.taskReviewUpdatingId,
    taskReviewKeyword: knowledgeSourcesDomain.taskReviewKeyword,
    taskReviewProviderFilter: knowledgeSourcesDomain.taskReviewProviderFilter,
    taskReviewStatusFilter: knowledgeSourcesDomain.taskReviewStatusFilter,
    taskReviewTypeFilter: knowledgeSourcesDomain.taskReviewTypeFilter,
    taskReviewActionFilter: knowledgeSourcesDomain.taskReviewActionFilter,
    taskReviewAnswerFilter: knowledgeSourcesDomain.taskReviewAnswerFilter,
    taskReviewPromotionTargetFilter: knowledgeSourcesDomain.taskReviewPromotionTargetFilter,
    taskReviewProviderOptions: knowledgeSourcesDomain.taskReviewProviderOptions,
    taskReviewStatusOptions: knowledgeSourcesDomain.taskReviewStatusOptions,
    taskReviewTypeOptions: knowledgeSourcesDomain.taskReviewTypeOptions,
    taskReviewActionFilterOptions: knowledgeSourcesDomain.taskReviewActionFilterOptions,
    taskReviewAnswerFilterOptions: knowledgeSourcesDomain.taskReviewAnswerFilterOptions,
    taskReviewPromotionTargetOptions: knowledgeSourcesDomain.taskReviewPromotionTargetOptions,
    taskReviewSessions: knowledgeSourcesDomain.taskReviewSessions,
    taskReviewSummaryCards: knowledgeSourcesDomain.taskReviewSummaryCards,
    selectedTaskReviewSessionId: knowledgeSourcesDomain.selectedTaskReviewSessionId,
    selectedTaskReviewSegmentId: knowledgeSourcesDomain.selectedTaskReviewSegmentId,
    selectedTaskReviewSession: knowledgeSourcesDomain.selectedTaskReviewSession,
    selectedTaskReviewItem: knowledgeSourcesDomain.selectedTaskReviewItem,
    promotionQueueLoading: knowledgeSourcesDomain.promotionQueueLoading,
    promotionQueue: knowledgeSourcesDomain.promotionQueue,
    promotionApplyingKey: knowledgeSourcesDomain.promotionApplyingKey,
    promotionPreviewOpen: knowledgeSourcesDomain.promotionPreviewOpen,
    promotionPreviewLoading: knowledgeSourcesDomain.promotionPreviewLoading,
    promotionPreviewError: knowledgeSourcesDomain.promotionPreviewError,
    promotionPreviewData: knowledgeSourcesDomain.promotionPreviewData,
    promotionViewerOpen: knowledgeSourcesDomain.promotionViewerOpen,
    promotionViewerLoading: knowledgeSourcesDomain.promotionViewerLoading,
    promotionViewerError: knowledgeSourcesDomain.promotionViewerError,
    promotionViewerTitle: knowledgeSourcesDomain.promotionViewerTitle,
    promotionViewerPaths: knowledgeSourcesDomain.promotionViewerPaths,
    promotionViewerNotes: knowledgeSourcesDomain.promotionViewerNotes,
    promotionSummaryCards: knowledgeSourcesDomain.promotionSummaryCards,
    healthLoading: knowledgeSourcesDomain.healthLoading,
    wikiHealth: knowledgeSourcesDomain.wikiHealth,
    healthSummaryCards: knowledgeSourcesDomain.healthSummaryCards,
    healthSeverityFilter: knowledgeSourcesDomain.healthSeverityFilter,
    healthCodeFilter: knowledgeSourcesDomain.healthCodeFilter,
    healthKeyword: knowledgeSourcesDomain.healthKeyword,
    healthCodeOptions: knowledgeSourcesDomain.healthCodeOptions,
    filteredHealthFindings: knowledgeSourcesDomain.filteredHealthFindings,
    healthFindingGroups: knowledgeSourcesDomain.healthFindingGroups,
    healthActionQueues: knowledgeSourcesDomain.healthActionQueues,
    selectedHealthFinding: knowledgeSourcesDomain.selectedHealthFinding,
    healthSuggestionState: knowledgeSourcesDomain.healthSuggestionState,
    healthBatchActionLoading: knowledgeSourcesDomain.healthBatchActionLoading,
    healthBatchActionLabel: knowledgeSourcesDomain.healthBatchActionLabel,
    healthRepairApplyingTarget: knowledgeSourcesDomain.healthRepairApplyingTarget,
    renderMarkdown: displayFormatDomain.renderMarkdown,
    setWorkbenchTab: knowledgeSourcesDomain.setWorkbenchTab,
    loadKnowledgeItems: knowledgeSourcesDomain.loadKnowledgeItems,
    loadTaskReviewSessions: knowledgeSourcesDomain.loadTaskReviewSessions,
    loadPromotionQueue: knowledgeSourcesDomain.loadPromotionQueue,
    loadWikiHealth: knowledgeSourcesDomain.loadWikiHealth,
    selectKnowledgeItem: knowledgeSourcesDomain.selectKnowledgeItem,
    selectTaskReviewSession: knowledgeSourcesDomain.selectTaskReviewSession,
    selectTaskReviewSegment: knowledgeSourcesDomain.selectTaskReviewSegment,
    selectHealthFinding: knowledgeSourcesDomain.selectHealthFinding,
    startNewKnowledgeItem: knowledgeSourcesDomain.startNewKnowledgeItem,
    saveKnowledgeItem: knowledgeSourcesDomain.saveKnowledgeItem,
    saveAndSubmitKnowledgeItem: knowledgeSourcesDomain.saveAndSubmitKnowledgeItem,
    updateKnowledgeItemStatus: knowledgeSourcesDomain.updateKnowledgeItemStatus,
    deleteKnowledgeItem: knowledgeSourcesDomain.deleteKnowledgeItem,
    openQuickCapture: knowledgeSourcesDomain.openQuickCapture,
    closeQuickCapture: knowledgeSourcesDomain.closeQuickCapture,
    saveQuickCapture: knowledgeSourcesDomain.saveQuickCapture,
    openBatchImport: knowledgeSourcesDomain.openBatchImport,
    closeBatchImport: knowledgeSourcesDomain.closeBatchImport,
    saveBatchImport: knowledgeSourcesDomain.saveBatchImport,
    openOpenClawSync: knowledgeSourcesDomain.openOpenClawSync,
    closeOpenClawSync: knowledgeSourcesDomain.closeOpenClawSync,
    previewOpenClawSync: knowledgeSourcesDomain.previewOpenClawSync,
    importOpenClawSync: knowledgeSourcesDomain.importOpenClawSync,
    applyTaskReviewAction: knowledgeSourcesDomain.applyTaskReviewAction,
    applyPromotionCandidate: knowledgeSourcesDomain.applyPromotionCandidate,
    dismissPromotionCandidate: knowledgeSourcesDomain.dismissPromotionCandidate,
    revokePromotionCandidate: knowledgeSourcesDomain.revokePromotionCandidate,
    previewPromotionCandidate: knowledgeSourcesDomain.previewPromotionCandidate,
    openPromotionEvidence: knowledgeSourcesDomain.openPromotionEvidence,
    openHealthFindingNote: knowledgeSourcesDomain.openHealthFindingNote,
    openHealthFindingEvidence: knowledgeSourcesDomain.openHealthFindingEvidence,
    openHealthQueueNotes: knowledgeSourcesDomain.openHealthQueueNotes,
    openHealthQueueEvidence: knowledgeSourcesDomain.openHealthQueueEvidence,
    loadHealthRepairSuggestions: knowledgeSourcesDomain.loadHealthRepairSuggestions,
    loadHealthAnchorSuggestions: knowledgeSourcesDomain.loadHealthAnchorSuggestions,
    previewHealthRepairSuggestion: knowledgeSourcesDomain.previewHealthRepairSuggestion,
    previewHealthAnchorSuggestion: knowledgeSourcesDomain.previewHealthAnchorSuggestion,
    batchDecideHealthStaleDraftIssues: knowledgeSourcesDomain.batchDecideHealthStaleDraftIssues,
    applyHealthRepairPlan: knowledgeSourcesDomain.applyHealthRepairPlan,
    applyHealthAnchorPlan: knowledgeSourcesDomain.applyHealthAnchorPlan,
    applyHealthRepairSuggestion: knowledgeSourcesDomain.applyHealthRepairSuggestion,
    vaultRebuildLoading: knowledgeSourcesDomain.vaultRebuildLoading,
    triggerVaultRebuild: knowledgeSourcesDomain.triggerVaultRebuild,
    cleanHealthBrokenEvidence: knowledgeSourcesDomain.cleanHealthBrokenEvidence,
    closePromotionPreview: knowledgeSourcesDomain.closePromotionPreview,
    closePromotionViewer: knowledgeSourcesDomain.closePromotionViewer,
  }

  const feishuSchedulePanelCtx = {
    isFeishuScheduleMode: flags.isFeishuScheduleMode,
    feishuScheduleDataFilter: bugInboxFeishuDomain.feishuScheduleDataFilter,
    setFeishuScheduleDataFilter: bugInboxFeishuDomain.setFeishuScheduleDataFilter,
    isFeishuScheduleDefectView: bugInboxFeishuDomain.isFeishuScheduleDefectView,
    isFeishuScheduleTodoView: bugInboxFeishuDomain.isFeishuScheduleTodoView,
    feishuTodoError: bugInboxFeishuDomain.feishuTodoError,
    feishuDefectError: bugInboxFeishuDomain.feishuDefectError,
    feishuTodoColumns: bugInboxFeishuDomain.feishuTodoColumns,
    feishuTodoItems: bugInboxFeishuDomain.feishuTodoItems,
    feishuTodoLoading: bugInboxFeishuDomain.feishuTodoLoading,
    FEISHU_TODO_COLUMN_WIDTHS_STORAGE_KEY: bugInboxFeishuDomain.FEISHU_TODO_COLUMN_WIDTHS_STORAGE_KEY,
    allFeishuTodoSelected: bugInboxFeishuDomain.allFeishuTodoSelected,
    toggleSelectAllFeishuTodos: bugInboxFeishuDomain.toggleSelectAllFeishuTodos,
    feishuTodoSelectedIds: bugInboxFeishuDomain.feishuTodoSelectedIds,
    asFeishuTodoRow: bugInboxFeishuDomain.asFeishuTodoRow,
    toggleFeishuTodoSelection: bugInboxFeishuDomain.toggleFeishuTodoSelection,
    getFeishuTodoDeadlineStatus: bugInboxFeishuDomain.getFeishuTodoDeadlineStatus,
    runFeishuTodoNextStep: bugInboxFeishuDomain.runFeishuTodoNextStep,
    feishuTodoNextStepLoadingId: bugInboxFeishuDomain.feishuTodoNextStepLoadingId,
    feishuDefectLoading: bugInboxFeishuDomain.feishuDefectLoading,
    feishuDefectItems: bugInboxFeishuDomain.feishuDefectItems,
    getFeishuCandidateKey: bugInboxFeishuDomain.getFeishuCandidateKey,
    getFeishuCandidateStatusTone: bugInboxFeishuDomain.getFeishuCandidateStatusTone,
    getFeishuCandidateAvatarText: bugInboxFeishuDomain.getFeishuCandidateAvatarText,
    getFeishuCandidateSeverity: bugInboxFeishuDomain.getFeishuCandidateSeverity,
    getFeishuCandidateSeverityLevel: bugInboxFeishuDomain.getFeishuCandidateSeverityLevel,
    getFeishuCandidateReporter: bugInboxFeishuDomain.getFeishuCandidateReporter,
    getFeishuCandidateCreatedAt: bugInboxFeishuDomain.getFeishuCandidateCreatedAt,
    getFeishuCandidateRequirement: bugInboxFeishuDomain.getFeishuCandidateRequirement,
    getFeishuCandidateDiscoveryStage: bugInboxFeishuDomain.getFeishuCandidateDiscoveryStage,
    getFeishuCandidateCategory: bugInboxFeishuDomain.getFeishuCandidateCategory,
    openFeishuCandidateUrl: bugInboxFeishuDomain.openFeishuCandidateUrl,
  }

  const sessionWorkspaceCtx = {
    sessionListCollapsed: uiState.sessionListCollapsed,
    keyword: uiState.keyword,
    useVectorSearch: uiState.useVectorSearch,
    loadSessions: sessionDataDomain.loadSessions,
    activeAdvancedFilterCount: sessionFilterDomain.activeAdvancedFilterCount,
    advancedFiltersOpen: uiState.advancedFiltersOpen,
    activeProvider: uiState.activeProvider,
    cursorConversationIdFilter: uiState.cursorConversationIdFilter,
    showRightProviderFilter: sessionFilterDomain.showRightProviderFilter,
    providerFilter: uiState.providerFilter,
    providers: sessionFilterDomain.providers,
    timeRangePreset: uiState.timeRangePreset,
    tagFilter: uiState.tagFilter,
    availableTags: sessionFilterDomain.availableTags,
    errorText: sessionDataDomain.errorText,
    importResultText: sessionDataDomain.importResultText,
    hasKeyword: sessionFilterDomain.hasKeyword,
    retrieving: sessionDataDomain.retrieving,
    retrieveMeta: sessionDataDomain.retrieveMeta,
    filteredSessions: sessionFilterDomain.filteredSessions,
    loading: sessionDataDomain.loading,
    selectedSession: sessionFlowDomain.selectedSession,
    selectedSessionId: uiState.selectedSessionId,
    getSessionDisplayTitle: sessionPresentationDomain.getSessionDisplayTitle,
    getSessionRefs: sessionPresentationDomain.getSessionRefs,
    formatScore: displayFormatDomain.formatScore,
    normalizeProviderId: sessionFilterDomain.normalizeProviderId,
    getProviderDisplayLabel: sessionFilterDomain.getProviderDisplayLabel,
    formatTime: displayFormatDomain.formatTime,
    getSessionMessageTags: sessionPresentationDomain.getSessionMessageTags,
    getTurnCount: sessionPresentationDomain.getTurnCount,
    openImportModal: importDomain.openImportModal,
    userAnchorIds: sessionFlowDomain.userAnchorIds,
    jumpToUserAnchor: sessionFlowDomain.jumpToUserAnchor,
    jumpToTurnIndex: sessionFlowDomain.jumpToTurnIndex,
    openDeleteConfirm: sessionDataDomain.openDeleteConfirm,
    updatingSessionReviewId: sessionDataDomain.updatingSessionReviewId,
    updateSessionReview: sessionDataDomain.updateSessionReview,
    deletingSessionId: sessionDataDomain.deletingSessionId,
    flowRef: uiState.flowRef,
    selectedSessionFlow: sessionFlowDomain.selectedSessionFlow,
    anchoredNodeId: uiState.anchoredNodeId,
    setFlowNodeRef: sessionFlowDomain.setFlowNodeRef,
    openPromptScoreModal: promptScoreDomain.openPromptScoreModal,
    openTagModal: messageTagDomain.openTagModal,
    renderMarkdown: displayFormatDomain.renderMarkdown,
    getAssistantDisplayChunks: sessionFlowDomain.getAssistantDisplayChunks,
  }

  const overlayModalsCtx = {
    uiToastQueue: uiToastDomain.uiToastQueue,
    removeUiToast: uiToastDomain.removeUiToast,
    importModalOpen: importDomain.importModalOpen,
    closeImportModal: importDomain.closeImportModal,
    folderInputRef: importDomain.folderInputRef,
    onFolderPicked: importDomain.onFolderPicked,
    importForm: importDomain.importForm,
    activeProviderLabel: importDomain.activeProviderLabel,
    triggerFolderSelect: importDomain.triggerFolderSelect,
    previewing: importDomain.previewing,
    importing: importDomain.importing,
    resetImportSelection: importDomain.resetImportSelection,
    previewImport: importDomain.previewImport,
    importFiles: importDomain.importFiles,
    importFolder: importDomain.importFolder,
    importPreview: importDomain.importPreview,
    quickCaptureOpen: knowledgeSourcesDomain.quickCaptureOpen,
    closeQuickCapture: knowledgeSourcesDomain.closeQuickCapture,
    quickCaptureSaving: knowledgeSourcesDomain.quickCaptureSaving,
    quickCaptureMode: knowledgeSourcesDomain.quickCaptureMode,
    quickCaptureSourceType: knowledgeSourcesDomain.quickCaptureSourceType,
    quickCaptureTitle: knowledgeSourcesDomain.quickCaptureTitle,
    quickCaptureContent: knowledgeSourcesDomain.quickCaptureContent,
    quickCaptureSourceUrl: knowledgeSourcesDomain.quickCaptureSourceUrl,
    quickCaptureTagsInput: knowledgeSourcesDomain.quickCaptureTagsInput,
    quickCaptureMarkActive: knowledgeSourcesDomain.quickCaptureMarkActive,
    quickCaptureProject: knowledgeSourcesDomain.quickCaptureProject,
    quickCaptureTopic: knowledgeSourcesDomain.quickCaptureTopic,
    quickCaptureIntakeStage: knowledgeSourcesDomain.quickCaptureIntakeStage,
    quickCaptureConfidence: knowledgeSourcesDomain.quickCaptureConfidence,
    quickCaptureDecisionNote: knowledgeSourcesDomain.quickCaptureDecisionNote,
    quickCapturePreview: knowledgeSourcesDomain.quickCapturePreview,
    quickCaptureBatchEntries: knowledgeSourcesDomain.quickCaptureBatchEntries,
    quickCaptureCanSave: knowledgeSourcesDomain.quickCaptureCanSave,
    quickCaptureSummary: knowledgeSourcesDomain.quickCaptureSummary,
    saveQuickCapture: knowledgeSourcesDomain.saveQuickCapture,
    embeddingBuildModalOpen: sessionDataDomain.embeddingBuildModalOpen,
    closeEmbeddingBuildModal: sessionDataDomain.closeEmbeddingBuildModal,
    embeddingBuildMode: sessionDataDomain.embeddingBuildMode,
    embeddingBuildStats: sessionDataDomain.embeddingBuildStats,
    embeddingBuildStatsLoading: sessionDataDomain.embeddingBuildStatsLoading,
    embeddingBuildPreview: sessionDataDomain.embeddingBuildPreview,
    embeddingBuildPreviewLoading: sessionDataDomain.embeddingBuildPreviewLoading,
    embeddingBuildJob: sessionDataDomain.embeddingBuildJob,
    rebuildingEmbeddings: sessionDataDomain.rebuildingEmbeddings,
    rebuildSessionEmbeddings: sessionDataDomain.rebuildSessionEmbeddings,
    loadEmbeddingBuildPreview: sessionDataDomain.loadEmbeddingBuildPreview,
    wikiVaultSyncModalOpen: wikiVaultSyncDomain.wikiVaultSyncModalOpen,
    closeWikiVaultSyncModal: wikiVaultSyncDomain.closeWikiVaultSyncModal,
    wikiVaultSyncMode: wikiVaultSyncDomain.wikiVaultSyncMode,
    wikiVaultSyncStats: wikiVaultSyncDomain.wikiVaultSyncStats,
    wikiVaultSyncStatsLoading: wikiVaultSyncDomain.wikiVaultSyncStatsLoading,
    wikiVaultSyncPreview: wikiVaultSyncDomain.wikiVaultSyncPreview,
    wikiVaultSyncPreviewLoading: wikiVaultSyncDomain.wikiVaultSyncPreviewLoading,
    wikiVaultSyncJob: wikiVaultSyncDomain.wikiVaultSyncJob,
    syncingWikiVault: wikiVaultSyncDomain.syncingWikiVault,
    wikiVaultProviderLabel: wikiVaultSyncDomain.wikiVaultProviderLabel,
    wikiVaultCanStart: wikiVaultSyncDomain.wikiVaultCanStart,
    loadWikiVaultSyncPreview: wikiVaultSyncDomain.loadWikiVaultSyncPreview,
    startWikiVaultSync: wikiVaultSyncDomain.startWikiVaultSync,
    modelSettingsOpen: modelSettingsDomain.modelSettingsOpen,
    closeModelSettings: modelSettingsDomain.closeModelSettings,
    modelSettingsLoading: modelSettingsDomain.modelSettingsLoading,
    modelSettingsSaving: modelSettingsDomain.modelSettingsSaving,
    modelSettingsDraft: modelSettingsDomain.modelSettingsDraft,
    modelCapabilities: modelSettingsDomain.modelCapabilities,
    enabledCapabilityCount: modelSettingsDomain.enabledCapabilityCount,
    selectedModelSettingsItem: modelSettingsDomain.selectedModelSettingsItem,
    modelSettingsTesting: modelSettingsDomain.modelSettingsTesting,
    modelSettingsTestResults: modelSettingsDomain.modelSettingsTestResults,
    saveModelSettings: modelSettingsDomain.saveModelSettings,
    resetModelSettingsDraft: modelSettingsDomain.resetModelSettingsDraft,
    testSelectedModelSettings: modelSettingsDomain.testSelectedModelSettings,
    feishuProjectSettingsOpen: feishuProjectSettingsDomain.feishuProjectSettingsOpen,
    feishuProjectSettingsLoading: feishuProjectSettingsDomain.feishuProjectSettingsLoading,
    feishuProjectSettingsSaving: feishuProjectSettingsDomain.feishuProjectSettingsSaving,
    feishuProjectSettingsError: feishuProjectSettingsDomain.feishuProjectSettingsError,
    feishuProjectSettings: feishuProjectSettingsDomain.feishuProjectSettings,
    feishuProjectSettingsDraft: feishuProjectSettingsDomain.feishuProjectSettingsDraft,
    feishuProjectSettingsModeLabel: feishuProjectSettingsDomain.feishuProjectSettingsModeLabel,
    closeFeishuProjectSettings: feishuProjectSettingsDomain.closeFeishuProjectSettings,
    resetFeishuProjectSettingsDraft: feishuProjectSettingsDomain.resetFeishuProjectSettingsDraft,
    saveFeishuProjectSettings: feishuProjectSettingsDomain.saveFeishuProjectSettings,
    patchDirSettingsOpen: patchDirSettingsDomain.patchDirSettingsOpen,
    closePatchDirSettings: patchDirSettingsDomain.closePatchDirSettings,
    patchDirDraftAlias: patchDirSettingsDomain.patchDirDraftAlias,
    patchDirDraftPath: patchDirSettingsDomain.patchDirDraftPath,
    patchDirAdding: patchDirSettingsDomain.patchDirAdding,
    patchDirEditingPresetId: patchDirSettingsDomain.patchDirEditingPresetId,
    patchDirTotal: patchDirSettingsDomain.patchDirTotal,
    editingPatchDirPreset: patchDirSettingsDomain.editingPatchDirPreset,
    selectedPatchDirPreset: patchDirSettingsDomain.selectedPatchDirPreset,
    startEditPatchDirPreset: patchDirSettingsDomain.startEditPatchDirPreset,
    cancelEditPatchDirPreset: patchDirSettingsDomain.cancelEditPatchDirPreset,
    addPatchDirPreset: patchDirSettingsDomain.addPatchDirPreset,
    patchDirPresets: patchDirSettingsDomain.patchDirPresets,
    selectedPatchDirPresetId: patchDirSettingsDomain.selectedPatchDirPresetId,
    removePatchDirPreset: patchDirSettingsDomain.removePatchDirPreset,
    deleteConfirmOpen: sessionDataDomain.deleteConfirmOpen,
    closeDeleteConfirm: sessionDataDomain.closeDeleteConfirm,
    pendingDeleteSession: sessionDataDomain.pendingDeleteSession,
    getSessionDisplayTitle: sessionPresentationDomain.getSessionDisplayTitle,
    deletingSessionId: sessionDataDomain.deletingSessionId,
    confirmDeleteSession: sessionDataDomain.confirmDeleteSession,
    bugInboxDeleteConfirmOpen: bugInboxFeishuDomain.bugInboxDeleteConfirmOpen,
    closeBugInboxDeleteConfirm: bugInboxFeishuDomain.closeBugInboxDeleteConfirm,
    bugInboxPendingDelete: bugInboxFeishuDomain.bugInboxPendingDelete,
    bugInboxDeletingId: bugInboxFeishuDomain.bugInboxDeletingId,
    confirmDeleteBugInbox: bugInboxFeishuDomain.confirmDeleteBugInbox,
    feishuBatchModalOpen: bugInboxFeishuDomain.feishuBatchModalOpen,
    closeFeishuBatchModal: bugInboxFeishuDomain.closeFeishuBatchModal,
    selectedFeishuTodos: bugInboxFeishuDomain.selectedFeishuTodos,
    feishuBatchAction: bugInboxFeishuDomain.feishuBatchAction,
    feishuBatchLoading: bugInboxFeishuDomain.feishuBatchLoading,
    feishuBatchRollbackReason: bugInboxFeishuDomain.feishuBatchRollbackReason,
    feishuBatchError: bugInboxFeishuDomain.feishuBatchError,
    feishuBatchResultText: bugInboxFeishuDomain.feishuBatchResultText,
    submitFeishuBatchTransition: bugInboxFeishuDomain.submitFeishuBatchTransition,
    tagModalOpen: messageTagDomain.tagModalOpen,
    closeTagModal: messageTagDomain.closeTagModal,
    tagModalTarget: messageTagDomain.tagModalTarget,
    presetTags: uiState.presetTags,
    tagModalSelected: messageTagDomain.tagModalSelected,
    toggleTagSelection: messageTagDomain.toggleTagSelection,
    tagModalSaving: messageTagDomain.tagModalSaving,
    saveMessageTags: messageTagDomain.saveMessageTags,
    promptScoreModalOpen: promptScoreDomain.promptScoreModalOpen,
    closePromptScoreModal: promptScoreDomain.closePromptScoreModal,
    promptScoreLoading: promptScoreDomain.promptScoreLoading,
    promptScoreError: promptScoreDomain.promptScoreError,
    promptScoreTaskType: promptScoreDomain.promptScoreTaskType,
    promptScoreResult: promptScoreDomain.promptScoreResult,
    promptEffectAssessmentLoading: promptScoreDomain.promptEffectAssessmentLoading,
    promptEffectAssessmentCacheLoading: promptScoreDomain.promptEffectAssessmentCacheLoading,
    promptEffectAssessmentError: promptScoreDomain.promptEffectAssessmentError,
    promptEffectAssessmentResult: promptScoreDomain.promptEffectAssessmentResult,
    getScoreRingStyle: promptScoreDomain.getScoreRingStyle,
    getScoreBand: promptScoreDomain.getScoreBand,
    getPromptTaskTypeLabel: promptScoreDomain.getPromptTaskTypeLabel,
    getPromptVerdictLabel: promptScoreDomain.getPromptVerdictLabel,
    getPromptScoreDimensions: promptScoreDomain.getPromptScoreDimensions,
    severityLabel: promptScoreDomain.severityLabel,
    promptScoreTargetText: promptScoreDomain.promptScoreTargetText,
    promptOptimizeLanguage: promptScoreDomain.promptOptimizeLanguage,
    promptOptimizeLoading: promptScoreDomain.promptOptimizeLoading,
    runPromptEffectAssessment: promptScoreDomain.runPromptEffectAssessment,
    runPromptOptimize: promptScoreDomain.runPromptOptimize,
    promptOptimizeResult: promptScoreDomain.promptOptimizeResult,
    promptOptimizeError: promptScoreDomain.promptOptimizeError,
    formatTime: displayFormatDomain.formatTime,
    renderMarkdown: displayFormatDomain.renderMarkdown,
    stripOuterCodeFence: promptScoreDomain.stripOuterCodeFence,
    collectPromptSources: promptScoreDomain.collectPromptSources,
    getSourceRadar: promptScoreDomain.getSourceRadar,
    getSourceLegend: promptScoreDomain.getSourceLegend,
    feishuBindModalOpen: bugInboxFeishuDomain.feishuBindModalOpen,
    closeFeishuBindModal: bugInboxFeishuDomain.closeFeishuBindModal,
    feishuBindTargetBug: bugInboxFeishuDomain.feishuBindTargetBug,
    feishuBindLoading: bugInboxFeishuDomain.feishuBindLoading,
    feishuBindError: bugInboxFeishuDomain.feishuBindError,
    feishuBindCandidates: bugInboxFeishuDomain.feishuBindCandidates,
    getFeishuCandidateKey: bugInboxFeishuDomain.getFeishuCandidateKey,
    isFeishuCandidateSelected: bugInboxFeishuDomain.isFeishuCandidateSelected,
    feishuBindLinkingKey: bugInboxFeishuDomain.feishuBindLinkingKey,
    selectFeishuCandidate: bugInboxFeishuDomain.selectFeishuCandidate,
    getFeishuCandidateStatusTone: bugInboxFeishuDomain.getFeishuCandidateStatusTone,
    getFeishuCandidateAvatarText: bugInboxFeishuDomain.getFeishuCandidateAvatarText,
    getFeishuCandidateSeverity: bugInboxFeishuDomain.getFeishuCandidateSeverity,
    getFeishuCandidateSeverityLevel: bugInboxFeishuDomain.getFeishuCandidateSeverityLevel,
    isFeishuCurrentBoundCandidate: bugInboxFeishuDomain.isFeishuCurrentBoundCandidate,
    getFeishuCandidateReporter: bugInboxFeishuDomain.getFeishuCandidateReporter,
    getFeishuCandidateCreatedAt: bugInboxFeishuDomain.getFeishuCandidateCreatedAt,
    getFeishuCandidateRequirement: bugInboxFeishuDomain.getFeishuCandidateRequirement,
    getFeishuCandidateDiscoveryStage: bugInboxFeishuDomain.getFeishuCandidateDiscoveryStage,
    getFeishuCandidateCategory: bugInboxFeishuDomain.getFeishuCandidateCategory,
    confirmFeishuBindSelection: bugInboxFeishuDomain.confirmFeishuBindSelection,
    feishuBindSelectedCandidateKey: bugInboxFeishuDomain.feishuBindSelectedCandidateKey,
    bugInboxDetailModalOpen: bugInboxFeishuDomain.bugInboxDetailModalOpen,
    closeBugInboxDetail: bugInboxFeishuDomain.closeBugInboxDetail,
    bugInboxDetailFields: bugInboxFeishuDomain.bugInboxDetailFields,
    copyBugDetailField: bugInboxFeishuDomain.copyBugDetailField,
  }

  return {
    bugLocatorPanelCtx,
    componentLibraryPanelCtx,
    modelManagementPanelCtx,
    knowledgeSourcesPanelCtx,
    feishuSchedulePanelCtx,
    sessionWorkspaceCtx,
    overlayModalsCtx,
  }
}
